version: "build-{build}"

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\raggaer\castro

environment:
  GOPATH: c:\gopath
  sshkey:
      secure: 8A7hSN8w1WV7V9wJY0gYT16obkQNObELp+IeNUcU5pQl3elU3ALzhyH2v1GZt/RhdQXeBTnvzUdRzyzc64qKcfqJXFZQ7FRo437PAR4xIkXe/Tejp5bwMBfrn9MJHMpmg2NGZO+Zi8lhwLsGKhiM39V3+U2gZivTaboQG2zoOwBbJLkRVeW4nReBFpQBQe6CvU4/UppaQMhGXTXbHSNPO5yYUaFgKpVdhbdhO9c51DH1TQrBBe4TlM+BxNPAOBs5E9OkaR+/xTA+B6o5cHeCtaqsuJ7uRU83p3Kp8jmGK5UMfUvgt3XeFNGGsF3fAgMw1jlHzWkL68zXZzUNDioeKr5mjexm/6RcZvOv6ati4p37swks6LN2chwBsemiLjJciHdxSWPPMo/sKpwTWy+JjevIVWqvW0L1MEHN+Pna200L4wNj6Vm2dh4pIybS1gsW2TQvEBquEnYsTQ9XyumpXC4BPhr13jhc7U5d0kQGIJ7ZXj3wtxYXlz9RR17EZJgNdAakfd1VsY1dpyPvffP529mqHqWoWZsL6orAj/Wp0vbaNYjnTdG6Rq7ib5x+MIQQJOrUWWkz3QREy5VLI515x5A4yKgaHB12KWH0P19vRLmGRxJFIbnICbC/xsKa1E8xWiOw3/qIEDxACbIXh5rotK9Ov5SPxUJ2Omu8+dbKk3EmIURZP3ZXnJxsCDzKYohd0bj+XiM4KXh8ls0PbfnrvcNgATY3gnDHebj3f4nL8l2w09+XkEi79mTrLath4D16i0R6IvsoYFBgwSMeibDXI5iEVpHkySGZhBsRBcFMVRtZE88d3iRNg7zsV7s1B6k5uwJo+QjZJx86fNJbaI364MDtUK3BGDCW1/WiJ15HNqLG58Daj8zMJ/zQRjcbgRcYAfbw4He0MZ2YE3sCl/b6zieCEUL2M8PmCH6L11DBfzfssOvCziilKbLfkkqylufnpyCcAgFxJ2clVioib6bJLbnie2eQveddrgbgIBs7TW6A7iU9c+1cf4oKzy/l3lVxNzq+W7p0b7bsjpzpFVAV7k4z13wAK+wGxtspjZXi2Jibp9z4XKjqYSexwaotZzR7CCacQivbEHN3GtTUv3O5Vg3ZPpjMW0Jcw+9ygGW95snkFfrLPqXfzL559E2alC/7cpQYjJq/Wb/CR4mwt8t4++z5Y6J/5a1+XjX7U9qKJ3s6tpC7PtX/IA++vyqE0yWQTJvsBLi5tV/VsDC+/mJZEAmQMhYH9q7gIBZUj4EOaSsLs210QxrIIw2zGYr4n2bEK6gyj9SHXfNjnOgBz4fOjB8r/rkkMHkoWNhouH7aE3LcpO2TrY73BGtQ42pBDcJP5pvDLHVXiUnoR2mrWba/GUuMx8aAsUSyiil0LvfeFaRRxkKtSF6PC6U3UTwncx23+qwt1aa5KHB07CyBQKAJ7B5RNWZ4Z7AnlPDLQ1f1B8kD/RMCyKsSSr+RwXMLh+hVwY4ZxEpSAcjw5DrYSg+NLLYZsfPKlyKGnrdVRna8122zDgdHiGifDtiuMIlcEPuxY93yxOnQjlLt9DsDWSFqESpWNpheLcPkgaV7h13cnqwkfFNnyx4Ca0MHDKe50IvlEdlHkTpIfBuak4L/AeZSReLoXeRLwpRhO54VAXFGAlP3ix8sAtQgP/IGgEqQdQ38a5ysTYmfh72ElCj0XR7fWaxse0tU9PGA8Z+9/XZKkqq2f2ED1m9x4fJwGKCGIA6SDf/kWmqM2w+/E8Fmz0xDB1n56RMKOcSVFtcLwcw86YmEKGi9kCdVe8pc7Gc1mQN6STKsS0JA4N8QqmN/aI9Eav0K6qIFtAwyB6tUczpX4f3ibQnhQBwrY3Pd74yhm2DWUnA5EwqtJ4YfS5JGvh0FLlYw5fK1PCzohP89Fs09JZFbY3oIuCYVc//epIUmJKkB


install:
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;%PATH%
  - go version
  - go env

build_script:
  - ps: .\appveyor_build.ps1

test: off

artifacts:
  - path: buildOutput\castro_win_amd64.exe
    name: Windows amd64 build
  - path: buildOutput\castro_linux_amd64
    name: Linux amd64 build
  - path: buildOutput\castro_linux_arm64
    name: Linux arm64 build
  - path: buildOutput\release.zip
    name: Required data